import { chromium, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
const token=readFileSync('../.env','utf8').match(/^SESSION_TOKEN=(.+)$/m)[1].trim().replace(/^['"]|['"]$/g,'');
const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:1400,height:1000}});
await page.goto('http://localhost:5173');
await page.getByRole('button',{name:'No, not now'}).click();
await page.locator('#pairing-token').fill(token);
await page.getByRole('button',{name:'Context',exact:true}).click();
await page.getByRole('switch',{name:'KBC Assist'}).click();
await expect(page.getByRole('button',{name:'Explore KBC car loan'})).toBeVisible({timeout:45000});
await page.getByRole('button',{name:'Explore KBC car loan'}).click();
await expect(page.getByRole('heading',{name:'Car loan',exact:true})).toBeVisible();
await page.screenshot({path:'artifacts/live-car-flow.png',fullPage:true});
await page.getByRole('button',{name:'Pause',exact:true}).click();
await expect(page.getByRole('status')).toContainText('Assist paused');
await expect(page.getByRole('button',{name:'Explore KBC car loan'})).toHaveCount(0);
await page.getByRole('button',{name:'Delete context',exact:true}).click();
await page.getByRole('button',{name:'Explore context',exact:true}).click();
await expect(page.getByText(/No context to show yet/)).toBeVisible();
await browser.close();
console.log('PASS: live capture, OCR, Interdict, cloud intent, car loan, pause and delete');